builds:
  - goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

dockers:
  - image_templates:
    - "vitalvas/git-backup:{{ .Tag }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: ghcr.io/vitalvas/git-backup:{{ .Tag }}
    image_templates:
      - ghcr.io/vitalvas/git-backup:{{ .Tag }}-amd64
  - name_template: ghcr.io/vitalvas/git-backup:latest
    image_templates:
      - ghcr.io/vitalvas/git-backup:{{ .Tag }}-amd64
